version: 2
formats:
  - pdf
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - opt
        - dev
    - method: setuptools
      path: .
sphinx:
  fail_on_warning: true
